const capitalCitiesArray = [
  [['England', 'London', 'This city is the capital of England.'],
    ['France', 'Paris', 'This city is the capital of France.'],
    ['Germany', 'Berlin', 'This city is the capital of Germany.'],
    ['Spain', 'Madrid', 'This city is the capital of Spain.'],
    ['Portugal', 'Lisbon', 'This city is the capital of Portugal.'],
    ['Netherlands', 'Amsterdam', 'This city is the capital of Netherlands.'],
    ['Ireland', 'Dublin', 'This city is the capital of Ireland.'],
    ['Belgium', 'Brussels', 'This city is the capital of Belgium.'],
    ['Italy', 'Rome', 'This city is the capital of Italy.'],
    ['Serbia', 'Belgrade', 'This city is the capital of Serbia.'],
    ['Denmark', 'Copenhagen', 'This city is the capital of Denmark.'],
    ['Sweden', 'Stockholm', 'This city is the capital of Sweden.'],
    ['Norway', 'Oslo', 'This city is the capital of Norway.']],

  [['Nigeria', 'Abuja', 'This city is the capital of Nigeria.'],
    ['Ghana', 'Accra', 'This city is the capital of Ghana.'],
    ['Algeria', 'Algiers', 'This city is the capital of Algeria.'],
    ['Morocco', 'Rabat', 'This city is the capital of Morocco.'],
    ['Egypt', 'Cairo', 'This city is the capital of Egypt.'],
    ['Kenya', 'Nairobi', 'This city is the capital of Kenya.'],
    ['Zimbabwe', 'Harare', 'This city is the capital of Zimbabwe.'],
    ['South Africa', 'Cape Town', 'This city is the capital of South Africa.']],

  [['Uruguay', 'Montevideo', 'This city is the capital of Uruguay.'],
    ['Brazil', 'Brasilia', 'This city is the capital of Brazil.'],
    ['Argentina', 'Buenos Aires', 'This city is the capital of Argentina.'],
    ['Chile', 'Santiago', 'This city is the capital of Chile.'],
    ['Columbia', 'Bogotá', 'This city is the capital of Columbia.'],
    ['Peru', 'Lima', 'This city is the capital of Peru.'],
    ['Mexico', 'Mexico City', 'This city is the capital of Mexico.']]
];
